encoding: "utf-8"
title: Magento Commerce Order Management Documentation
email: mailto:skolodyazhnyy@magento.com
description: Magento Commerce Order Management
baseurl: "/docs"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
incremental: true
githuburl: https://github.com/magento-mcom/docs/tree/gh-pages/
specificationurl: https://magento-mcom.github.io/shared-services-internal/specification.json
sass:
  sass_dir: theme/_scss/
  style: compressed
